version: '3'
services:
  webserver:
    build: .
    container_name: test-app
    volumes:
      - ../:/var/www/html
    ports:
      - "9003:80"
    networks:
      - indiemassive
    depends_on:
      - test-db
      - test-redis
    command: >
        bash -c "echo 'DocumentRoot /var/www/html/public' > /etc/apache2/sites-available/000-default.conf && apache2-foreground"


  test-db:
    image: mariadb:latest
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33306:3306"
    networks:
      - indiemassive

  test-redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "36079:6379"
    networks:
      - indiemassive

networks:
  indiemassive:
    driver: bridge
